### ISSUE TITLE
add namespace to `nomad_job`

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/terraform-provider-nomad#125]
some users have requested the ability to specify the `namespace` on a nomad job without having explicitly putting it into the job spec. this can be done by taking the existing computed attribute `namespace` and allowing it to be (optionally) specified.

specifically, would like to be able to do something like this: 
```hcl
provider "nomad" {
  address = "http://localhost:4646"
}

resource "nomad_namespace" "mynamespace" {
  name = "mynamespace"
}

resource "nomad_job" "myjob" {
  jobspec = file("${path.module}/myjob.nomad")
  detach = false
  namespace = nomad_namespace.mynamespace.name
}
```

**Comment by cgbaker** [comment]
because this is a computed field, making it also `optional` (so that users can specify it) causes a bunch of problems with the terraform plugin SDK, as it currently stands. we can revisit this later; they plan is to provide a new Nomad job resource which is structured to allow all viable fields at the top level.

**Comment by lgfa29** [comment]
Closing this for now as it has the same underlying issue of #1. We will address this problem in #149.
