### ISSUE TITLE
Request: nomad_job + deployment to completion?

### ISSUE THREAD

**Issue by chuckyz** [hashicorp/terraform-provider-nomad#146]
I'm unsure where to request this, but with the discussion in #1 about opening up nomad jobs the way they are, could we use deployment data resources to watch nomad jobs to completion?

I'm imagining a pure terraform workflow of actually watching job deployments to success.

Basically...

```
resource "nomad_job" "foo" {
  region = "dc1"
  datacenters = ["dc1"]
  task_group {
    task { name = "foo" }
  }
}

data "nomad_deployment" "foo_job" {
  deployment_id = nomad_job.foo.deployment_id
}

resource "null_resource" "foo" {
  wait_for = nomad_deployment.foo_job.deployment_status == "complete"
}
```

I understand that the above is wrong/won't work.  However, I'd like to get some community thoughts on if this work pattern would be useful for others, and from folks working with terraform providers if this would ever be possible.

I also understand that this will _never_ work as intended for batch or system jobs.

**Comment by cgbaker** [comment]
@chuckyz , the Nomad resource already supports this. Setting the `detach` field ([docs](https://registry.terraform.io/providers/hashicorp/nomad/latest/docs/resources/job#detach)) to `false` will cause the provider to wait for the deployment to complete during create/update.

**Comment by chuckyz** [comment]
Well heck, I'm gonna close this up and get new glasses then!
