### ISSUE TITLE
Feature idea: nomad_datacenter data source

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/terraform-provider-nomad#151]
Similar to the nomad_namespaces that provides a list of known nomad namespaces, it would be nice to have an equivalent data source that could list the datacenters in a given cluster.  This would make re-usable terraform modules much easier and more automatic.

**Comment by lgfa29** [comment]
Thanks for the idea @the-maldridge!

The Nomad API doesn't have an endpoint to list datacenters, but this seems to be doable using the [`GET /v1/nodes`](https://www.nomadproject.io/api-docs/nodes#list-nodes) endpoint and iterating over the list, collecting the set of datacenters along the way.

This list would change as nodes are added or removed, so we will need to make sure to handle this.

**Comment by the-maldridge** [comment]
@lgfa29 interesting!  I thought it was really clever when the datacenters filter showed up in the UI a few releases ago, but it seems like that may be making more requests than I thought originally.

I think its probably okay for it to be correct at the time of read, my intended use case is to get the list of datacenters to feed into a nomad_job and push a system job to all machines.

**Comment by the-maldridge** [comment]
Thanks!

**Comment by lgfa29** [comment]
No problem! I'm glad I was able to squeeze this one into the release 😄
