### ISSUE TITLE
New Resource - Operator Scheduler Configurations

### ISSUE THREAD

**Issue by codyja** [hashicorp/terraform-provider-nomad#153]
It would be fantastic if we could get support for managing the new Scheduler Configuration. I'm specifically interested in managing SchedulerAlgorithm=spread for example. Here's a link to the api section describing this:
https://www.nomadproject.io/api-docs/operator#scheduleralgorithm-1

**Comment by jrasell** [comment]
Hi @codyja and thanks for taking the time to write this up. I agree, this would be a very useful addition to the provider.
