### ISSUE TITLE
Terraform leaves orphant periodic jobs after destroying parent

### ISSUE THREAD

**Issue by mahsoud** [hashicorp/terraform-provider-nomad#154]
Terraform v0.12.28
provider hashicorp/nomad v1.4.9

### Nomad Version
nomad.version 0.12.3
nomad.revision 2db8abd9620dd41cb7bfe399551ba0f7824b3f61

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
```hcl
provider nomad {
  address   = var.NOMAD_ADDR
  secret_id = var.NOMAD_TOKEN
}

resource nomad_job this {
  jobspec                 = file("${path.module}/nomad_job.tpl")
  deregister_on_destroy   = true
  deregister_on_id_change = true
  detach                  = false
}
```

Sample job file:

```hcl
job "scenario-validation" {
  datacenters = ["mio"]
  type = "batch"

  periodic {
    cron      = "0 2,17,32,47 * * * * *"
    time_zone = "Etc/UTC"
  }

  group "testing" {
    task "test" {

      driver = "raw_exec"
      config {
        command = "powershell.exe"
        args = [
          "-NoProfile",
          "-ExecutionPolicy",
          "Bypass",
          "-Command",
          "Write-Host",
          "Hello"
        ]
      }

      template {
        destination   = "sample.csv"
        data          = <<EOH
sample
EOH
      }
      
      restart {
        attempts = 1
        mode     = "fail"
      }
    }
  }
}
```

### Expected Behavior
Not sure if this should be handled by the provider or nomad server itself.

### Actual Behavior
Orphant jobs remain in a pending state after the destruction of the parent job.

### Steps to Reproduce
1. `terraform apply`
2. Wait for few jobs to be created in a pending state
3. `terraform destroy`

**Comment by cgbaker** [comment]
Can you please provide the `job status` and `job inspect` for the parent job and one of the periodic children?

**Comment by mahsoud** [comment]
nomad job status scenario-validation
Prefix matched multiple jobs
```
ID                                                                   Type   Priority  Status          Submit Date
scenario-validation/periodic-1600777800  batch  50        dead (stopped)  2020-09-22T15:30:00+03:00
scenario-validation/periodic-1600785300  batch  50        pending         2020-09-22T17:35:00+03:00
scenario-validation/periodic-1600785600  batch  50        pending         2020-09-22T17:40:00+03:00
```

**Comment by lgfa29** [comment]
Thanks for the extra info @mahsoud. Do these pending job eventually complete? Or is the problem that they remain stuck at pending after running `terraform destroy`?

**Comment by lgfa29** [comment]
Hi @mahsoud 👋 

just checking in to see if you happen to have any update on this?
