### ISSUE TITLE
Feature request: Add key connect.gateway in nomad_job.jobspec

### ISSUE THREAD

**Issue by cageyv** [hashicorp/terraform-provider-nomad#155]
### Terraform Version
0.13.4 

### Nomad Version
0.12.5

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
- ingress.hcl
```hcl
job "ingress" {
  datacenters = ["dc1"]
  group "ingress" {
    network {
      port "inbound" {
        static = 8080
      }
    }
    service {
      name = "ingress-service"
      port = "8080"
      connect {
        gateway {
          proxy {
            connect_timeout = "500ms"
          }
          ingress {
            tls {
              enabled = false
            }
            listener {
              port     = 8080
              protocol = "http"
              service {
                name  = "web"
                hosts = ["example.com", "example.com:8080"]
              }
            }
            listener {
              port     = 3306
              protocol = "tcp"
              service {
                name  = "database"
              }
            }
          }
        }
      }
    }
  }
}
```
- main.tf
```hcl
provider "nomad" {
  address = "http://127.0.0.1:4646"
}

data "template_file" "ingress" {
  template = file("${path.module}/ingress.hcl")
}

resource "nomad_job" "ingress" {
  jobspec          = data.template_file.ingress.rendered
}
```

### Expected Behavior
https://www.nomadproject.io/docs/job-specification/gateway#gateway-stanza 

### Actual Behavior
```
Error: error parsing jobspec: error parsing 'job': 1 error occurred:
        * group: 'ingress', service (0): 'ingress-service', connect -> invalid key: gateway
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
https://www.consul.io/docs/connect/gateways
[parse_service.go#L146](https://github.com/hashicorp/terraform-provider-nomad/blob/517ba3bcba226abf135b09a5d839c8144da4d479/nomad/core/jobspec/parse_service.go#L146)

UDP:
If we try to write a configuration in json format, we will get an error about the [absence of a gateway](https://github.com/hashicorp/nomad/blob/8a448f02741a48c701c45ac10c37c752e7ff8c3a/nomad/structs/services.go#L764) because parse_service.go don't parse gateway. 
Right now is no way for deploy gateways with provider.  I think json + direct API call will be useful now.

**Comment by lgfa29** [comment]
Closed by #158
