### ISSUE TITLE
Timeline for next release?

### ISSUE THREAD

**Issue by rigrassm** [hashicorp/terraform-provider-nomad#159]
First off, thank you guys for the excellent work!

In #145, support for `mount_options` was added for volume registration and this is something that we are eagerly awaiting as it removes the last part of our deployment that relies on work being done manually with the nomad binary.

I'm guessing the wait to make another release since that PR was merged was due to the Nomad 1.0 release (which actually fixed a blocker for us with CSI which now works on 1.0) and was curious if there was any general estimate for when we might see another release?

Thanks again!

**Comment by cgbaker** [comment]
working on it right now!
https://github.com/hashicorp/terraform-provider-nomad/pull/158
should be a release tomorrow

**Comment by rigrassm** [comment]
@cgbaker, perfect timing, thank you!

**Comment by lgfa29** [comment]
The new version is out now 🎉 

I am going to close this issue, but feel free to open a new one if you have any problems with the new `mount_point` attribute.
