### ISSUE TITLE
Namespaces are part of OSS as of 1.0.0

### ISSUE THREAD

**Issue by lsc** [hashicorp/terraform-provider-nomad#176]
The Terraform registry page for the Nomad provider [here](https://registry.terraform.io/providers/hashicorp/nomad/latest/docs/resources/namespace) has a warning box at the top that says that the API endpoint is only part of Enterprise. 

As of Nomad 1.0.0, the Namespaces part is distributed with the OSS releases.

**Comment by cgbaker** [comment]
thanks, @lsc
