### ISSUE TITLE
HTTP Basic Auth Support

### ISSUE THREAD

**Issue by thebeanogamer** [hashicorp/terraform-provider-nomad#180]
It would be really useful if the provider supported HTTP Basic Auth in the same way [hashicorp/terraform-provider-consul](https://github.com/hashicorp/terraform-provider-consul/) does. Whilst ACLs should provide the same level of security, an additional layer would be useful for workloads such as using the provider in Terraform Cloud to manage on-prem Nomad deployments. I'm sadly not familiar enough with Terraform provider development to implement this myself, but I'm happy to test an implementation from someone else if one is made.

Edit: As the module supports mutual TLS (or at least appears to from the docs), this is not the only solution, however basic auth can be a way of achieving a slightly lower level of security but a lot faster for people bootstrapping their first environment.

**Comment by macnibblet** [comment]
You can actually already do this by adding it to address in the provider. But it would be a lot better if this was more consistent.

```
provider "nomad" {
  address = "https://username:password@example.com"
}
```
