### ISSUE TITLE
v1.4.12 - Incompatible API version with plugin

### ISSUE THREAD

**Issue by Xopherus** [hashicorp/terraform-provider-nomad#194]
### Terraform Version

0.11.14

### Nomad Version

0.12.6

### Provider Configuration

1.4.12

### Expected Behavior

The plan to be created with `terraform plan`. 

### Actual Behavior

The plan failed with the above error:

```bash
terraform-0.11.14 init 
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "template" (2.2.0)...
- Downloading plugin for provider "null" (2.1.2)...
- Downloading plugin for provider "nomad" (1.4.12)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.nomad: version = "~> 1.4"
* provider.null: version = "~> 2.1"
* provider.template: version = "~> 2.2"

Terraform has been successfully initialized!
terraform-0.11.14 plan -out terra.plan

Error: Error asking for user input: 1 error occurred:
	* provider.nomad: Incompatible API version with plugin. Plugin version: 5, Core version: 4
```

### Important Factoids

We're not version capping the nomad provider, so we have (until today) been pulling in the latest provider version. We did not start to see this problem until provider version 1.4.12 (released today).

**Comment by Xopherus** [comment]
It seems as this is probably related to the bump in terraform-plugin-sdk, which went from v1.16 (provider version 1.4.11) to v2.4 (provider version 1.4.12). v2 of the plugin sdk does not support Terraform < 0.12, but this provider does. 

Shouldn't this update have been been a major version update, not a bugfix?

**Comment by lgfa29** [comment]
Hi @Xopherus,

You are right, the update to Terraform SDK v2 broke support for Terraform 0.11.x, which was an unintended consequence and we are sorry for that.

We will revert to SDK v1 until our next major release and publish a new version soon. In the meantime, you can pin the provider version to 0.14.11 so you are not blocked by this.

**Comment by Xopherus** [comment]
Appreciate the follow up and thanks for clarifying @lgfa29 ! When do you think we can expect a new version?

**Comment by lgfa29** [comment]
@Xopherus the release is out, but it might still take a few minutes for the Terraform registry to refresh.

While this was an unintended upgrade, we do plan to drop support for Terraform v0.11.x [at some point this year](https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers), so it's recommended to upgrade it if possible. 

When it happens, we will make sure it is handled properly and with advanced notice (unlike in this case). There are mechanisms in Terraform to prevent it from downloading incompatible providers, so we will make sure to use them.

Thanks for the patience and apologies for this issue once again.
