### ISSUE TITLE
Unable to build 1.4.13 or 1.4.12 using go install - GO version 1.13.15 and Terraform 0.12.21 , 1.4.11 and before works fine - Arch: ppc64le

### ISSUE THREAD

**Issue by bhadrim** [hashicorp/terraform-provider-nomad#199]
I am trying to build the provider in ubuntu ppc64le using go install. While go install works fine on 1.4.11, it fails on  1.4.13 and 1.4.12 with the following error. Thank you.

build github.com/hashicorp/terraform-provider-nomad: cannot load github.com/hashicorp/nomad/api: unzip /usr/local/gopath/pkg/mod/cache/download/github.com/hashicorp/nomad/@/v1.0.2.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot

### Terraform Version
0.12.21

### Nomad Version
1.4.13 / 1.4.12

### Provider Configuration
NA

### Environment Variables
NA

### Affected Resource(s)
NA

### Terraform Configuration Files
NA

### Debug Output
HEAD is now at 71a883a v1.4.13
go: downloading github.com/zclconf/go-cty v1.4.1
go: downloading github.com/oklog/run v1.0.1-0.20180308005104-6934b124db28
go: downloading github.com/hashicorp/hcl v1.0.1-0.20201016140508-a07e7d50bbee
go: downloading github.com/hashicorp/nomad v1.0.2
go: extracting github.com/oklog/run v1.0.1-0.20180308005104-6934b124db28
go: extracting github.com/zclconf/go-cty v1.4.1
go: extracting github.com/hashicorp/hcl v1.0.1-0.20201016140508-a07e7d50bbee
go: downloading github.com/hashicorp/hcl/v2 v2.7.1-0.20201020204811-68a97f93bb48
go: downloading golang.org/x/sys v0.0.0-20200728102440-3e129f6d46b1
go: extracting github.com/hashicorp/hcl/v2 v2.7.1-0.20201020204811-68a97f93bb48
go: extracting golang.org/x/sys v0.0.0-20200728102440-3e129f6d46b1
go: downloading github.com/aws/aws-sdk-go v1.35.3
go: extracting github.com/hashicorp/nomad v1.0.2
-> unzip /usr/local/gopath/pkg/mod/cache/download/github.com/hashicorp/nomad/@v/v1.0.2.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot
go: extracting github.com/aws/aws-sdk-go v1.35.3
go: finding github.com/hashicorp/hcl v1.0.1-0.20201016140508-a07e7d50bbee
go: finding github.com/hashicorp/hcl/v2 v2.7.1-0.20201020204811-68a97f93bb48
go: finding github.com/zclconf/go-cty v1.4.1
go: finding golang.org/x/sys v0.0.0-20200728102440-3e129f6d46b1
go: finding github.com/aws/aws-sdk-go v1.35.3
go: finding github.com/oklog/run v1.0.1-0.20180308005104-6934b124db28
build github.com/hashicorp/terraform-provider-nomad: cannot load github.com/hashicorp/nomad/api: unzip /usr/local/gopath/pkg/mod/cache/download/github.com/hashicorp/nomad/@/v1.0.2.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot

### Panic Output
NA

### Expected Behavior
What should have happened?

Get the binary for the provider.

### Actual Behavior
What actually happened?

Failed with error

build github.com/hashicorp/terraform-provider-nomad: cannot load github.com/hashicorp/nomad/api: unzip /usr/local/gopath/pkg/mod/cache/download/github.com/hashicorp/nomad/@/v1.0.2.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot

### Steps to Reproduce
1. Clone the repo (1.4.13/1.4.12) in ppc64le
2. execute go install 

### Important Factoids
Using Power PC 64 bit LE

### References
NA

**Comment by lgfa29** [comment]
Hi @bhadrim,

Thanks for reporting this issue. In versions 1.4.12 and 1.4.13 we added support for HCL2 jobspec parsing, which a bit more complex that HCL1.

Previously we were copying and syncing the jobspec parsing logic from the Nomad repo, which is not great. But with HCL2 we had to import the Nomad, which is also not ideal.

Cross-compiling seems to work from an `amd64` machine, but I don't have a `ppc64le` environment to test if the binary actually runs.

Could you try cross-compiling it in a different arch?

```
env GOOS=linux GOARCH=ppc64le go build
```

**Comment by lgfa29** [comment]
Hi @bhadrim,

I am going to close this issue for now since there hasn't been any new activity in a while. Feel free to let us know if you have any updates and we can re-open it.
