### ISSUE TITLE
Unable to Deploy Nomad Jobs When Consul 'allow_unauthenticated' Flag Set

### ISSUE THREAD

**Issue by nallana** [hashicorp/terraform-provider-nomad#200]
### Terraform Version
```
Terraform v0.14.5
```

### Nomad Version

```
❯ nomad server members
Name                           Address      Port  Status  Leader  Protocol  Build  Datacenter  Region
[REDACTED].us-east-1  10.0.73.241  4648  alive   true    2         1.0.2  us-east-1   us-east-1
[REDACTED].us-east-1  10.0.54.125  4648  alive   false   2         1.0.2  us-east-1   us-east-1
[REDACTED].us-east-1  10.0.93.50   4648  alive   false   2         1.0.2  us-east-1   us-east-1
```

### Provider Configuration

```hcl
provider "nomad" {
  address = "https://${data.terraform_remote_state.nomad_servers.outputs.nomad_servers_dns_record}"		
}
```

### Environment Variables

```sh
env | grep "NOMAD_"
```

N/A - Using Terraform Cloud

Environment variables set there are:

```sh
NOMAD_TOKEN=***
NOMAD_SKIP_VERIFY=true
VAULT_TOKEN=***
CONSUL_HTTP_TOKEN=***
```

### Affected Resource(s)

- nomad_job

### Terraform Configuration Files

```sh
cat system/ingress_gateways.tf
```

```hcl
resource "nomad_job" "ingress_gateway_http" {
  jobspec = file("${path.module}/jobs/system-ingress-gateway-http.nomad")
}
```

```sh
cat system/jobs/system-ingress-gateway-http.nomad
```

```hcl
job "system-ingress-gateway-http" {
  datacenters = ["us-east-1"]

  type = "system"
  
  group "ingress-group" {

    network {
      mode = "bridge"

      port "inbound" {
        static = 8080
        to     = 8080
      }
    }

    service {
      name = "ingress-gateway-http"
      port = "8080"

      connect {
        gateway {

          proxy { }

          ingress {
            tls {
              enabled = true
            }

            listener {
              port     = 8080
              protocol = "tcp"

              service {
                name = "[REDACTED]"
              }
            }
          }
        }		
      }
    }
  }
}
```

### Expected Behavior

Terraform plan and apply are able to deploy the Ingress Gateway job to the Nomad server.

### Actual Behavior

Terraform is unable to deploy the Ingress Gateway job to the Nomad server. Output:

```
Terraform v0.14.5
Initializing plugins and modules...
nomad_job.ingress_gateway_http: Creating...

Error: error applying jobspec: Unexpected response code: 500 (rpc error: operator token denied: missing consul token)

  on ingress_gateways.tf line 1, in resource "nomad_job" "ingress_gateway_http":
   1: resource "nomad_job" "ingress_gateway_http" {
```

Setting the same environment variables and deploying manually using `nomad job run system-ingress-gateway-http.nomad` deploys the job successfully.

Submitting Nomad jobs that are not ingress-gateway types works successfully through Terraform with the same setup above. Unverified hypothesis is that this applies to all jobs need operator ACL permissions.

**Update**: applies to non-gateway jobs as well.

### Steps to Reproduce

Terraform plan and apply through Terraform Cloud. Plan succeeds, but apply fails.

### Important Factoids

```sh
cat images/nomad-ami-ubuntu18/nomad/config/client.json
```

```json
{
    "client": {
        "enabled": true
    },
    "consul": {
        "address": "127.0.0.1:8501",
        "allow_unauthenticated": false
    }
...
}
```

```sh
cat images/nomad-ami-ubuntu18/nomad/config/server.json
```

```json
{
    "server": {
        "enabled": true,
        "bootstrap_expect": 3,
    },
    "consul": {
        "address": "127.0.0.1:8501",
        "allow_unauthenticated": false
    },
    ...
}
```

```sh
cat images/nomad-ami-ubuntu18/vault/templates/reload_nomad_server.sh
```

```sh
#!/bin/bash

readonly CONSUL_HTTP_TOKEN=$(cat /opt/vault/data/consul-token-nomad | xargs)
readonly VAULT_TOKEN=$(cat /opt/vault/data/nomad-vault-token | xargs)

cat /opt/nomad/config/agent.json.tpl | \
    jq --arg token $CONSUL_HTTP_TOKEN '.consul += { token: $token }' \
    > /opt/nomad/config/agent.json

printf "VAULT_TOKEN=$VAULT_TOKEN\n" > /opt/nomad/config/agent.env
printf "CONSUL_HTTP_TOKEN=$CONSUL_HTTP_TOKEN\n" >> /opt/nomad/config/agent.env
printf "CONSUL_HTTP_ADDR=127.0.0.1:8501\n" >> /opt/nomad/config/agent.env
printf "CONSUL_GRPC_ADDR=127.0.0.1:8502\n" >> /opt/nomad/config/agent.env

sudo systemctl restart nomad_server.service
```

The CONSUL_HTTP_TOKEN in reload_nomad_server.sh was derived from the following policy:

```sh
cat policies/role_nomad_server.tf
```

```hcl

...

resource "consul_acl_policy" "nomad_servers" {
  name        = local.nomad_server_vault_agent_role

  rules       = <<-RULE
    service_prefix "" {
      policy = "write"
    }
    node_prefix "" {
      policy = "write"
    }
    agent_prefix "" {
      policy = "write"
    }
    acl = "write"
    operator = "write"
RULE

...

}
```

The CONSUL_HTTP_TOKEN set in the Terraform environment was the **Bootstrap Token (Global Management)** token.

**Comment by nallana** [comment]
**Update: the above seems to also be the case for non-gateway jobs.**

Modified the provider to set the job ConsulToken parameter during job submission to match what appears to be happening in the CLI code, and that fixes the issue.

---

Changes: https://github.com/dystr-dev/terraform-provider-nomad/commit/4c6fa265b0127db703442f79b756c903f6738ce4

---

Please advise if looking at this wrong. 

Using this for now on our end. For others stuck and need an answer, feel free to use this patched version in the interim:

```hcl
terraform {
  required_providers {
    nomad = {
      source = "dystr-dev/nomad"
      version = "1.4.15"
    }
  }
}

provider "nomad" {
  # Configuration options
}
```

**Comment by lgfa29** [comment]
Thanks for the update @nallana! And I'm glad you were able to find a fix that works for you.

I haven't had the time to look deeper into the issue, but it does seem like you are correct and we are not parsing the Consul token properly.

I think a better approach would be to handle the Consul token similarly to how the [Vault token](https://github.com/hashicorp/terraform-provider-nomad/blob/master/nomad/provider.go#L168-L177) is handled, so it can be set in the provider and then [used by resources](https://github.com/hashicorp/terraform-provider-nomad/blob/master/nomad/resource_job.go#L735-L736).

If you would be interested in opening a PR with this fix we will be happy to review! Otherwise I will try tackling this in the coming days.
