### ISSUE TITLE
Update Nomad API for 1.0.4 and terminating gateway support.

### ISSUE THREAD

**Issue by alexdulin** [hashicorp/terraform-provider-nomad#201]
Nomad 1.0.4 released support for specifying terminating gateways within the `service.connect.gateway` stanza, but the current version of the Nomad API used by this provider does not include the `terminating` gateway type. It would be great if the provider could get a bump of the Nomad API to include support for the new gateway type.

**Comment by ElfoLiNk** [comment]
@jrasell could you please release a new version with this ? thanks
