### ISSUE TITLE
gateway -> invalid key: terminating

### ISSUE THREAD

**Issue by Lucretius** [hashicorp/terraform-provider-nomad#214]
### Terraform Version
This is being built in CI/CD using a docker container (hashicorp/terraform:0.14.9)

### Nomad Version
Running the `nomad server members` command shows all servers are using Build 1.0.4

### Provider Configuration

```hcl
provider "nomad" {}
```

Provider-wise, the logs indicate that the provider is using the latest one which supports the new 1.0.4 syntax.  I've gone and pinned the version to this latest one just in case.
```
Initializing provider plugins...
- Finding hashicorp/nomad versions matching "1.4.14"...
- Installing hashicorp/nomad v1.4.14...
- Installed hashicorp/nomad v1.4.14 (signed by HashiCorp)
```
### Environment Variables
Do you have any Nomad specific environment variable set in the machine running Terraform?

```sh
NOMAD_ADDR
NOMAD_REGION
NOMAD_TOKEN
```

### Affected Resource(s)
Please list the resources as a list, for example:
- nomad_job

### Terraform Configuration Files
```hcl
job "test" {
  region      = "testregion"
  datacenters = ["us-west-2"]
  type        = "service"

  vault {
    policies = ["nomad_vault"]
  }

  constraint {
    attribute = "$${attr.kernel.name}"
    value     = "linux"
  }

  group "gateway" {
    network {
      mode = "bridge"
    }

    service {
      name = "terminating-gateway"
      connect {
        gateway {
          proxy {

          }
          terminating {
            service {
              name = "tgw-service"
            }
          } 
        }
      }
    }
  } 
  
  ...other services...
}
```

### Expected Behavior
The Terraform Nomad job should run a plan without issue.

### Actual Behavior
The job does not understand the 1.0.4 Terminating Gateway syntax.

```
Error: error parsing jobspec: error parsing 'job': group: 'gateway', service (0): 'terminating-gateway', gateway, 1 error occurred:
	* gateway -> invalid key: terminating
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
ACL is enabled and the token is being provided to Nomad via the `NOMAD_TOKEN` env var.  I have gone in and created a terminating gateway by manually altering the JSON of the job, so I can confirm that terminating gateways can be created using my Nomad cluster - it is just the Nomad provider that does not understand it.  Also, if I just comment out the gateway group the plan completes without issue, so there is no issue communicating with Nomad itself.

**Comment by lgfa29** [comment]
Thanks for the report @Lucretius.

#206 updated the Nomad API package, so this field should've been parsed correctly. 

We'll investigate this further and get back to you.
