### ISSUE TITLE
darwin_arm64 support

### ISSUE THREAD

**Issue by yaleman** [hashicorp/terraform-provider-nomad#217]
### Terraform Version

```
$ terraform -v
Terraform v0.14.8
```

### Nomad Version

n/a

### Provider Configuration
(irrelevant, but here you go)

```hcl
provider "nomad" {
  address = "https://example.com"
}
```

### Environment Variables

n/a

### Affected Resource(s)

All, it's the provider itself.

### Terraform Configuration Files

n/a

### Debug Output
```
terraform init
Initializing the backend...
Initializing provider plugins...
- Finding latest version of hashicorp/nomad...
Error: Incompatible provider version
Provider registry.terraform.io/hashicorp/nomad v1.4.14 does not have a package
available for your current platform, darwin_arm64.
```

### Expected Behavior

I should be able to use it on an M1 mac.

### Actual Behavior

Terraform failed to `init`.

### Steps to Reproduce

1. `terraform init`

### Important Factoids

Apple silicon requires a new architecture build.

**Comment by jrasell** [comment]
Hi @yaleman and thanks for raising this issue. This is certainly something we want to support.

**Comment by yaleman** [comment]
Thanks for the confirmation - happy to provide testing if needed :)

**Comment by bigmstone** [comment]
I was able to compile locally and get myself going pretty easily, but yes +1 to registry support. So far no issues on `darwin_arm64`. Was able to apply job spec through it.

**Comment by bflad** [comment]
Just adding a reference link to the Terraform CLI issue as well: https://github.com/hashicorp/terraform/issues/27257
