### ISSUE TITLE
Support for job.group.consul block in nomad_job

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/terraform-provider-nomad#220]
### Terraform Version

Terraform: 0.14.11
Terraform-provider-nomad: 1.4.14

### Nomad Version

1.1.0-beta1

### Provider Configuration

```hcl
provider "nomad" {}
```

### Environment Variables

`NOMAD_ADDR` and `NOMAD_TOKEN` are set appropriately

### Affected Resource(s)

- nomad_job

### Terraform Configuration Files
```hcl
resource "nomad_job" "test" {
  jobspec = <<-EOT
   ##..
  group "test" {
    consul {
      namespace = "default"
    }
  }
  # ..
  EOT
  hcl2 {
    enabled = true
  }
}
```

### Expected Behavior

Job should be parsed correctly and submitted to Nomad for execution

### Actual Behavior

```
Terraform v0.14.11
Configuring remote state backend...
Initializing Terraform configuration...
# ..

Error: error parsing jobspec: :74,5-11: Unsupported block type; Blocks of type "consul" are not expected here.

  on nomad_consul_test.tf line 1, in resource "nomad_job" "test":
   1: resource "nomad_job" "test" {
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Likely the provider needs rebuilding against the nomad 1.1.0-beta+ SDK to support the new specification jobs in 1.1.0

**Comment by jrasell** [comment]
Thanks @optiz0r, this is something we will certainly get updated and sorted.
