### ISSUE TITLE
Request to add ssh bastion

### ISSUE THREAD

**Issue by bugchecker** [hashicorp/terraform-provider-nomad#237]
Terraform cannot connect to nomad server through ssh (or vpn?) tunnel (without external assistance)

### Terraform Version
```sh
$ terraform -v
Terraform v0.15.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.44.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/nomad v1.4.15
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.0. You can update by downloading from https://www.terraform.io/downloads.htm
```

### Nomad Version
```sh
$ nomad server members
Name                     Address        Port  Status  Leader  Protocol  Build  Datacenter  Region
ip-172-31-53-139.global  172.31.53.139  4648  alive   true    2         1.1.1  dc1         global
$ nomad --version
Nomad v1.1.1 (7feec97c04de4f8afff54ca9e56d66a61dfbfeb3)
```

### Provider Configuration
```hcl
provider nomad {
  address = "http://${var.deploy-servers.hashicorp.server.private_ip}:4646"
}
```

### Environment Variables
Do you have any Nomad specific environment variable set in the machine running Terraform?

```sh
$  env | grep "NOMAD_"
$
```

### Affected Resource(s)
```hcl
resource nomad_job test {
  jobspec    = <<-EOT
    job "${var.environment}-test" {
      type = "service"
      affinity {
        attribute = "environment"
        value     = "${var.environment}"
        weight    = 100
      }
      group "${var.environment}-test" {
        affinity {
          attribute = "target"
          value     = "test"
          weight    = 100
        }
        task "${var.environment}-sleep" {
          driver = "raw_exec"
          user   = "ubuntu"
          config {
            command = "/bin/sleep"
            args    = ["1"]
          }
          resources {
            cpu    = 20
            memory = 10
          }
          logs {
            max_files     = 3
            max_file_size = 10
          }
        }
      }
    }
    EOT
}
```

### Terraform Configuration Files
...

### Debug Output
...

### Panic Output
```
module.dev.nomad_job.test: Creating...
module.dev.nomad_job.test: Still creating... [10s elapsed]
module.dev.nomad_job.test: Still creating... [20s elapsed]
module.dev.nomad_job.test: Still creating... [30s elapsed]
╷
│ Error: error applying jobspec: Put "http://172.31.53.139:4646/v1/jobs": dial tcp 172.31.53.139:4646: i/o timeout
│ 
│   with module.dev.nomad_job.test,
│   on environment/main.tf line 212, in resource "nomad_job" "test":
│  212: resource nomad_job test {
│ 
```

### Expected Behavior
...

### Actual Behavior
...

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jrasell** [comment]
Hi @bugchecker and thanks for opening this issue.

In the provider configuration you detail that you are using the Nomad server private IP address as the endpoint; this is subsequently resulting in the i/o timeout error when performing the Terraform apply. Does the machine you are running the Terraform commands from have routable access to  `172.31.53.139:4646`? Performing a command such as `curl -v 172.31.53.139:4646/v1/status/leader` would help display this.

You mention the use of ssh tunnels, along with the successful output of `nomad server members` without setting the address of the Nomad API endpoint. The Nomad CLI uses a Nomad address default of `http://127.0.0.1:4646` which when combined with the previous details, leads me to believe you're running an ssh tunnel linking 127.0.0.1:4646 -> 172.31.53.139:4646 (local -> remote). If this is the case, then the provider configuration should look like the following to utilise the tunnel, as `172.31.53.139` is not routable from your machine directly.

```
provider nomad {
  address = "http://127.0.0.1:4646"
}
```

Looking forward to hear your feedback.

**Comment by bugchecker** [comment]
Yes. I wish to deploy job from external CI/CD (from internet). So I supposed do it like connection in remote-exec (it has bastion arguments), because I don't know the best practices for deploying nomad jobes

**Comment by lgfa29** [comment]
Hi @bugchecker.

`remote-exec` is a provisioner, so they work differently from providers. Setting up the network connection to Nomad is outside the scope of the provider.

You would need to either expose the Nomad API is a controlled way (using firewalls, VPC peering, ACLs etc), or run or CI/CD worker within your private network.
