### ISSUE TITLE
Support for job.group.consul block in nomad_job (non-hcl2)

### ISSUE THREAD

**Issue by saltxwater** [hashicorp/terraform-provider-nomad#241]
### Terraform Version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/nomad v1.4.15

### Nomad Version
1.1.2+ent

### Provider Configuration
Which values are you setting in the provider configuration? 

```hcl
provider "nomad" { }
```

### Environment Variables
NOMAD_ADDR and NOMAD_TOKEN are set appropriately

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
```hcl
resource "nomad_job" "test" {
  jobspec = <<-EOT
   ##..
  group "test" {
    consul {
      namespace = "default"
    }
  }
  # ..
  EOT
}
```

### Expected Behavior
Job should be parsed correctly and submitted to Nomad for execution

### Actual Behavior
```
Error: error parsing jobspec: error parsing 'job': 1 error occurred:
        * group: 'test' -> invalid key: consul
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
This is a duplicate of the fixed issue:
https://github.com/hashicorp/terraform-provider-nomad/issues/220
However with hcl2 not-enabled.
The parser goes through a different code path when hcl2 is not enabled and I don't think this parser has been fixed:
https://github.com/hashicorp/terraform-provider-nomad/blob/main/nomad/resource_job.go#L738

### References
https://github.com/hashicorp/terraform-provider-nomad/issues/220

**Comment by jrasell** [comment]
Hi @saltxwater and thanks for taking the time to fill this detailed issue. This is related to the fact that Nomad was not updating the hclv1 parser to include new functionality until recently, where we decided to change approach and keep the hclv1 and hclv2 parser harmonised. This work was conducted within https://github.com/hashicorp/nomad/pull/10931 and is pending release. I will work on updating the dependancy to fix this issue.

**Comment by lgfa29** [comment]
Closed by https://github.com/hashicorp/terraform-provider-nomad/pull/256
