### ISSUE TITLE
Nomad Job file for Consul Mesh Gateway does not parse in the Terraform Nomad Provider.

### ISSUE THREAD

**Issue by CarelvanHeerden** [hashicorp/terraform-provider-nomad#246]
Hi there,

### Terraform Version
Terraform v1.0.5
hashicorp/nomad v1.4.15

### Nomad Version
nomad server members
Name             Address     Port  Status  Leader  Protocol  Build  Datacenter  Region
consul000000.eu  X.X.2.8   4648  alive   false   2         1.1.2  GENERAL     eu
consul000001.eu  X.X.2.9   4648  alive   true    2         1.1.2  GENERAL     eu
consul000002.eu  X.X.2.10  4648  alive   false   2         1.1.2  GENERAL     eu
consul000000.sa  Y.Y4.4    4648  alive   false   2         1.1.2  GENERAL     sa
consul000001.sa  Y.Y.4.5    4648  alive   true    2         1.1.2  GENERAL     sa
consul000002.sa  Y.Y.4.6    4648  alive   false   2         1.1.2  GENERAL     sa

### Provider Configuration
Which values are you setting in the provider configuration?

```hcl
provider "nomad" {
  address = lookup(var.nomad_address, terraform.workspace)
  region  = "sa"
}

provider "nomad" {
  address = lookup(var.nomad_address_eu, terraform.workspace)
  region  = "eu"
  alias   = "eu"
}
```

### Affected Resource(s)
Please list the resources as a list, for example:
- nomad_job
```hcl
job "mesh-eu" {
  datacenters = ["GENERAL"]

  group "mesh-gateway-eu" {
    network {
      mode = "bridge"
      port "mesh_vpn" {
        host_network = "default"
      }
    }
    service {
      name = "mesh-gateway"
      port = "mesh_vpn"

      connect {
        gateway {
          mesh {
          }
          proxy {
          }
        }
      }
    }
  }
}
```

### Expected Behavior
I expect this simple mesh gateway to be pushed with TF to Nomad.

### Actual Behavior
When running the above manually via the Nomad UI, the job gets created. No errors. However, when trying to push the job via Terraform:

```
│ Error: error parsing jobspec: error parsing 'job': group: 'mesh-gateway-eu', service (0): 'mesh-gateway', gateway, 1 error occurred:
│ 	* gateway -> invalid key: mesh
│ 
│ 
│ 
│   with module.mesh-gatewau.nomad_job.mesh_eu[0],
│   on modules/nomad_jobs/Mesh/main.tf line 1, in resource "nomad_job" "mesh_eu":
│    1: resource "nomad_job" "mesh_eu" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by lgfa29** [comment]
> Looking at Nomad changelog: _Connect Mesh Gateways_ was added in version 1.1.1, and the go.mod has `github.com/hashicorp/nomad v1.1.0`... The latest Nomad ver is 1.1.6. @lgfa29 is there any chance that can be bumped and a new release soon?

Yes, I'm prerping for a new release based on Nomad 1.2.0 that will be out soon. 

We usually update on X.Y.0 releases since that's when major new features come out, but Mesh Gateways was kind of an odd ball...

**Comment by grahambrown11** [comment]
Thanks - look forward to the new release

**Comment by grahambrown11** [comment]
@lgfa29 sorry to be a nag, but now that Nomad 1.2.0 is officially released, how much longer before we see the provider release?

**Comment by lgfa29** [comment]
Hi @grahambrown11. Yes, we will have a new release early next week. I'm just wrapping up some of the remaining open issues 🙂

**Comment by lgfa29** [comment]
Closed by https://github.com/hashicorp/terraform-provider-nomad/pull/256
