### ISSUE TITLE
Inconsistent Final Plan when Nomad Job ID changes in a generated jobspec

### ISSUE THREAD

**Issue by sgtang** [hashicorp/terraform-provider-nomad#248]
### Terraform Version
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/nomad v1.4.15

### Nomad Version
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)

### Provider Configuration
Which values are you setting in the provider configuration? 

```
provider "nomad" {
  address = "https://nomad.${var.env}.company.com:443"
  region  = "global"
}
```

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
```
# This null_resource runs a script to generate a Nomad HCL file based on a given user test.yaml
resource "null_resource" "generate_nomad" {
  provisioner "local-exec" {
    command = "generate_nomad_job test.yaml"
  }

  triggers = {
    config_hash = sha256(file("${path.root}/test.yaml"))
  }
}

# This data source reads the generated Nomad HCL jobspec
data "local_file" "generated_nomad" {
  depends_on = [
    null_resource.generate_nomad
  ]
  filename = "${path.root}/generated_nomad.hcl"

}

# This resource registers a Nomad job based on the generated Nomad HCL jobspec above
resource "nomad_job" "test" {

  jobspec = data.local_file.generated_nomad.content
  deregister_on_destroy = true
  purge_on_destroy = true

  hcl2 {
    enabled = true
  }
}
```

### Debug Output
https://gist.github.com/sgtang/a96e55e813e873fc1027845629acb5d4

### Expected Behavior
Nomad provider shouldn't change an update-in-place to a create/destroy.

### Actual Behavior
Nomad changed an update-in-place to a create/destroy, causing Terraform to error out on apply.

### Steps to Reproduce
1. `terraform apply` (and create initial resources successfully)
2. Change the Nomad job name/ID in test.yaml, which will cause a regeneration of the jobspec on next apply
3. `terraform apply` again

Not sure if this can be easily fixed, but essentially since the job ID is a computed field in `nomad_job`, and we're using a data source to read a Nomad HCL jobspec that is generated on-the-fly, the provider doesn't know that the job ID is changed until after the data source is read, meaning that during the plan it shows up as an update-in-place. After the provider computes a change in the ID, then the operation becomes a DeleteThenCreate, causing the apply to error out.

On the next rerun of apply, since the generated file already exists, the provider correctly registers the DeleteAndCreate, however it would be ideal if we could both generate a new Nomad file and create the new job in the same apply operation.

*Wanted to note that we currently work around this by first running a targeted apply on the `null_resource` and `local_file` resources, and then an apply on the `nomad_job` itself, but we're not sure if the provider should be able to handle the case where all three are changed within the same apply.

**Comment by lgfa29** [comment]
Hi @sgtang 👋 

Unfortunately I don't think there's a way around this. The job name is its ID, so changing it dynamically is not recommended, though possible if the change is well-defined.

The problem in this case is that Terraform can't do multi-stage planning. The job ID is dependent on the template, which is also a dynamic and non-known value at plan time, so the Terraform doesn't know that the job ID will change.

If you plan on modifying the job ID it's best to delete the old job with a `terraform destroy` and always create the dynamic job from a fresh state.

I hope this helps!

**Comment by lgfa29** [comment]
Forgot to mention this, but for future reference, here are the reproduction files I used
https://gist.github.com/lgfa29/05d2562e81a0135bb0c5cb0252920942
