### ISSUE TITLE
Release with darwin/arm64 Support for Apple M1 processors

### ISSUE THREAD

**Issue by spuder** [hashicorp/terraform-provider-nomad#254]
Related to https://github.com/hashicorp/terraform/issues/28041#issuecomment-964689464

If you try and use this provider on an apple M1 cpu, you get the following error

```
terraform providers lock \
-platform=windows_amd64 \
-platform=darwin_amd64 \
-platform=linux_amd64 \
-platform=darwin_arm64 \
-platform=linux_arm64
- Fetching hashicorp/nomad 1.4.11 for windows_amd64...
- Obtained hashicorp/nomad checksums for windows_amd64 (signed by HashiCorp)
- Fetching hashicorp/nomad 1.4.11 for darwin_amd64...
- Obtained hashicorp/nomad checksums for darwin_amd64 (signed by HashiCorp)
- Fetching hashicorp/nomad 1.4.11 for linux_amd64...
- Obtained hashicorp/nomad checksums for linux_amd64 (signed by HashiCorp)
╷
│ Error: Could not retrieve providers for locking
│ 
│ Terraform failed to fetch the requested providers for darwin_arm64 in order to calculate their checksums: some providers could not be installed:
│ - registry.terraform.io/hashicorp/nomad: provider registry.terraform.io/hashicorp/nomad 1.4.11 is not available for darwin_arm64.
```

Please release `darwin_arm64` versions of this provider so Apple M1 users can use terraform with nomad. 

The `consul` and `vault` providers by comparison already have darwin_arm64 builds. See 
- https://github.com/hashicorp/terraform-provider-consul/issues/253
- https://github.com/hashicorp/terraform-provider-vault/issues/1038

Related: https://github.com/actions/virtual-environments/issues/2187

**Comment by spuder** [comment]
https://github.com/actions/virtual-environments/issues/2187

**Comment by spuder** [comment]
@bflad You released the `darwin/arm64` builds for vault/consul. Is this something you could help with for nomad?

**Comment by lgfa29** [comment]
Hi @spuder 👋 

The latest release includes ARM builds for Darwin: 
https://releases.hashicorp.com/terraform-provider-nomad/1.4.16/terraform-provider-nomad_1.4.16_darwin_arm64.zip

Could you give a try and see if that works for you?

**Comment by spuder** [comment]
Yes, worked, thank you very much

```
terraform providers lock \
-platform=windows_amd64 \
-platform=darwin_amd64 \
-platform=linux_amd64 \
-platform=darwin_arm64 \
-platform=linux_arm64
- Fetching hashicorp/nomad 1.4.15 for windows_amd64...
- Obtained hashicorp/nomad checksums for windows_amd64 (signed by HashiCorp)
- Fetching hashicorp/nomad 1.4.15 for darwin_amd64...
- Obtained hashicorp/nomad checksums for darwin_amd64 (signed by HashiCorp)
- Fetching hashicorp/nomad 1.4.15 for linux_amd64...
- Obtained hashicorp/nomad checksums for linux_amd64 (signed by HashiCorp)
- Fetching hashicorp/nomad 1.4.15 for darwin_arm64...
- Obtained hashicorp/nomad checksums for darwin_arm64 (signed by HashiCorp)
- Fetching hashicorp/nomad 1.4.15 for linux_arm64...
- Obtained hashicorp/nomad checksums for linux_arm64 (signed by HashiCorp)

Success! Terraform has updated the lock file.
```

**Comment by Shaja-dev** [comment]
> Hi @spuder 👋
> 
> The latest release includes ARM builds for Darwin: https://releases.hashicorp.com/terraform-provider-nomad/1.4.16/terraform-provider-nomad_1.4.16_darwin_arm64.zip
> 
> Could you give a try and see if that works for you?

with what application should I OPEN IT?

**Comment by lgfa29** [comment]
Hi @Shaja-dev,

I'm not sure I understand the question. Terraform providers are automatically downloaded by Terraform for the correct platform you're using. Check https://developer.hashicorp.com/terraform/language/providers for more information.
