### ISSUE TITLE
cannot detect change when an external file (template) changes

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/terraform-provider-nomad#263]
### Terraform Version
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.5.0
+ provider registry.terraform.io/hashicorp/nomad v1.4.16

### Nomad Version
1.2.6

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
N/A

### Expected Behavior
Scenario: Using the `nomad_job` resource, which contains a `template` block. The `data` is from an external file:

```hcl
      template {
        data        = file("runme.bash")
        destination = "local/runme.bash"
      }
```
If there is a change in the file `runme.bash`, `terraform plan` fails to detect an overall change in the job definition.

### Actual Behavior
The terraform provider should understand the change.
Doing a direct `nomad job plan` shows the expected change, so the issue is with the nomad provider.

### Steps to Reproduce
From the above example, make a change in the file `runme.bash` and try a `terraform plan`. It shows nothing. It should show the diff.

**Comment by lgfa29** [comment]
Hi @shantanugadgil 👋 

This is how Terraform works, so there is nothing that the provider can do about it. If there isn't any trackable change that Terraform can see it doesn't even call the provider. 

If you need to track changes to external files you will need to load them as a data source and pass it to the job resource. Here's the documentation about it: 
https://registry.terraform.io/providers/hashicorp/nomad/latest/docs/resources/job#filesystem-functions

I'm going to close this one, but let me know if I'm missing something and we can re-open it.
