### ISSUE TITLE
nomad_job is put in a nonexistent namespace by default

### ISSUE THREAD

**Issue by dysonfrost** [hashicorp/terraform-provider-nomad#267]
### Terraform Version
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/nomad v1.4.16

### Nomad Version
Nomad v1.2.6 or v1.3.0

### Provider Configuration

```hcl
provider "nomad" {
  address = var.NOMAD_ADDR
  region  = "global"
}
```

### Affected Resource(s)

- nomad_job

### Terraform Configuration Files
```hcl
resource "nomad_job" "webapp" {
  jobspec = file("${path.module}/jobs/webapp.nomad")
  hcl2 {
    enabled = true
  }
}
```

### Debug Output
- TF_LOG_PROVIDER output: https://gist.github.com/dysonfrost/17afb60e0da0b56b926c465f19aee616
- Terraform plan output: https://gist.github.com/dysonfrost/663bc6458cf05f456d8844c130ba1166
- Nomad log sample output: https://gist.github.com/dysonfrost/3fa04875fb85f85bf8dd516d5f7d08d8

### Expected Behavior
Webapp job should have been put in the `default` namespace

### Actual Behavior
Terraform makes a request to put the job in the `isolation` namespace

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

Until last week I had no issue with this configuration, but since today I cannot create/modify a `nomad_job` resource.
The `isolation` namespace doesn't exist in the terraform state and nomad namespaces list.
Same result when I specifically declare another namespace that already exists.
I am using Terraform Cloud, also tried to run the job directly with Nomad 1.2.6 and 1.3.0, it works as expected.

**Comment by JRPCF** [comment]
I am also having this issue with terraform cloud using a private provider for Nomad (a fork of terraform-aws-nomad v0.10.0) and Nomad ~> 1.4.15

**Comment by konsti** [comment]
I have the same issue:

Nomad version: `1.1.3`
Nomad Terraform module pinned to `1.4.15`

**Comment by lgfa29** [comment]
Hi everyone 👋 

We found out what was causing this issue. An update in the TFC environment made the `NOMAD_NAMESPACE` env var to be set in the TFC runner environment, and this value was being picked up accidentally by the provider.

#271 will fix this by making sure a namespace is never set at the provider level.

**Comment by lgfa29** [comment]
Hi all, a quick update on this.

We received reports that some users were relying on the `NOMAD_NAMESPACE` env var so we had to essentially rollback the change made in 1.4.17. 

But v1.1.18 will still ignore `NOMAD_NAMESPACE` if the provider detects that it's running within Terraform Cloud (by inspecting the `TFC_RUN_ID` env var). If, for some reason, this automatic detection fails, you can force the provider to ignore the env var by using the new `ignore_env_vars` configuration:

```hcl
# After upgrading to 1.4.18
provider "nomad" {
  ignore_env_vars = {
    NOMAD_NAMESPACE: true,
  }
}
```

Let us know if this doesn't work for you 🙂
