### ISSUE TITLE
TFC overrides the default region("global") by "tf-cloud-iso-prod-use1"

### ISSUE THREAD

**Issue by lens0021** [hashicorp/terraform-provider-nomad#274]
### Terraform Version
`Terraform v1.2.4`

### Nomad Version

`Nomad v1.3.1 (2b054e38e91af964d1235faa98c286ca3f527e56)`

### Provider Configuration

```hcl
provider "nomad" {
  address   = var.nomad_address
}

resource "nomad_job" "memcached" {
  jobspec = file("memcached.nomad")
  detach  = false
}
```

`memcached.nomad`:
```hcl
job "memcached" {
  datacenters = ["dc1"]

  group "memcached" {
    task "memcached" {
      driver = "docker"

      config {
        image = "memcached:1.6.15-alpine"
      }
    }
  }
}
```

([See the full code here](https://gitlab.com/lens0021/terraform-nomad-provider-workspace-sample))

### Debug Output
> **Error: error applying jobspec: Unexpected response code: 500 (No path to region)**
with nomad_job.memcached
on base.tf line 29, in resource "nomad_job" "Memcached":
> ```
> resource "nomad_job" "memcached" {
> ```

### Panic Output

> 2022-07-07T10:46:05.769+0900 [WARN]  nomad.rpc: no path found to region: region=tf-cloud-iso-prod-use1
> 2022-07-07T10:46:05.770+0900 [ERROR] http: request failed: method=GET path="/v1/job/memcached?namespace=default&region=tf-cloud-iso-prod-use1" error="No path to region" code=500

### Expected Behavior
I didn't set the region, so the default value `"global"` should be used.

### Actual Behavior
The region seems to be set to `"tf-cloud-iso-prod-use1"`.

### Steps to Reproduce

1. Setup a workspace with the Remote execution mode.
2. Start new run on TFC.
3. Apply.

And as a workaround:

1. Adding `region = "global"` makes the problem disappear.

### References

GH-267 is very similar to this. The problem has shown up without code changes since someday.

**Comment by oinkbark** [comment]
I had basically the same issue of the default "global" region being overridden, but it was simply not being set to anything.
This was the error that was producing for all of my jobs:
```
Error: error checking for job: Unexpected response code: 500 (No path to region)
```
Provider version: 1.4.17 (Previously 1.4.15)
Nomad Version: 1.3.2 (Previously 1.0.4)

I also did not make any code changes and it appeared out of nowhere. I wasn't on these latest versions but upgraded to see if it would resolve the problem (and didn't). I tried hardcoding the global region into the jobspecs and the server config, but that also made no difference.

The workaround I found is to manually harcode the global region into the provider config:
```tf
provider "nomad" {
  address =  var.address
  region = "global"
}
```

**Comment by lgfa29** [comment]
Thank you for the report @lens0021. 

As @oinkbark mentioned, you explicit set a region for now. I will work on a fix to ignore the `NOMAD_REGION` env var (an add a config to opt-in in loading it like https://github.com/hashicorp/terraform-provider-nomad/pull/280).

**Comment by lgfa29** [comment]
Hi everyone 👋 

Version 1.4.18 just went out and I think it will make this problem go away. It will ignore the `NOMAD_REGION` environment variable by default if the provider detects that it's running in Terraform Cloud (by checking the existence of the `TFC_RUN_ID` env var).

If, for some reason, this still doesn't work for you, there's a new configuration to force the env var to be ignored:

```hcl
provider "nomad" {
  ignore_env_vars = {
    NOMAD_REGION: true,
  }
}
```

Let us know if this doesn't fix the problem for you 🙂
