### ISSUE TITLE
New uid/gid parameters in template stanza are marked as unsupported arguments

### ISSUE THREAD

**Issue by kjschubert** [hashicorp/terraform-provider-nomad#279]
Hi there,

I have a nomad jobspec written in HCL2 which uses the uid and gid attributes in the template stanza. When I try to deploy this job via the terraform provider the following error appears:
```
Error: error parsing jobspec: :399,9-12: Unsupported argument; An argument named "uid" is not expected here.
 :400,9-12: Unsupported argument; An argument named "gid" is not expected here.
```

Those attributes were introduced in Nomad 1.3.3 (see https://github.com/hashicorp/nomad/releases/tag/v1.3.3). The go.mod File of this terraform provider still imports version 1.3.1.
https://github.com/hashicorp/terraform-provider-nomad/blob/a5881e0e49b3591becd281a69a21377e635e598d/go.mod#L24

### Terraform Version
```
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/nomad v1.4.17
```

### Nomad Version
3 Controllers plus 2 Clients all running Version 1.3.3

### Provider Configuration
```hcl
provider "nomad" {
  address   = "..."
  secret_id = ...
  ca_pem    = ...
}
```

### Affected Resource(s)
nomad_job

### Terraform Configuration Files
```hcl
resource "nomad_job" "postgres" {
  hcl2 {
    enabled = true
    vars = {
      ...
    }
  }
  detach  = false
  jobspec = file("${path.module}/files/jobspec.hcl")
}
```

Jobspec (relevant part):
```
job "..." {
  group "..." {
    task "..." {
      template {
        data          = ...
        destination   = ...
        change_mode   = "signal"
        change_signal = "SIGHUP"
        uid           = 999
        gid           = 999
        perms         = 600
      }
    }
  }
}
```

### Expected Behavior
Successfully validate the jobspec and submit the job

### Actual Behavior
uid and gid attributes in template stanza are marked as unsupported argument

**Comment by tgross** [comment]
Hi @kjschubert! That'll be fixed by https://github.com/hashicorp/terraform-provider-nomad/pull/278 and will ship in the next release. Thanks!
