### ISSUE TITLE
[query] use semantic versioning to match the `consul` (or `aws`) provider

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/terraform-provider-nomad#296]
I have always wondered why the Nomad provider DOES NOT follow the semantic versioning style of the `consul` (or `aws`) provider.

The last digit is mostly zero, unless it is an emergency "spotfix".

_I could understand if the first two digits were matching the current latest GA of Nomad, but that doesn't seem to be the case either._

Thus, I propose that the next version be `1.5.0`, rather than incrementing the third digit. :slightly_smiling_face:

**Comment by jrasell** [comment]
Hi @shantanugadgil and thanks for raising this issue. This makes sense and matching other providers should be the way forward. I'll leave this open for other engineers and community member comments.

**Comment by shantanugadgil** [comment]
I think the new proposed version number of `2.0.0` might be a good starting point for this change. Keeping an :eye:  on this one till then.

**Comment by lgfa29** [comment]
Yup, that's the plan. Starting with 2.0.0 we'll adhere to a semver approach 👍 

Thanks for the raising the issue.

**Comment by lgfa29** [comment]
`v2.0.0-beta.1` is released (it may take a moment to show up in the registry), so I'm closing this one as complete. 

Thanks for the suggestion @shantanugadgil!

**Comment by shantanugadgil** [comment]
Now that even 1.6.1 is out, when would the 2.0.0 GA be coming! :hourglass_flowing_sand:

**Comment by lgfa29** [comment]
There are a few extra changes I want to get into v2.0.0, but we should have a GA release shortly 🤞
