### ISSUE TITLE
nomad ceph csi volume parameters

### ISSUE THREAD

**Issue by NegativeFeedback** [hashicorp/terraform-provider-nomad#297]
When I attempt to use the provider to create a ceph volume, it fails because it does not seem to accept parameters as a config value even though I believe I am following the documentation.

### Terraform Version
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/nomad v1.4.16
+ provider registry.terraform.io/hashicorp/vault v3.5.0

### Nomad Version
1.4.2

### Affected Resource(s)

- nomad_volume

### Terraform Configuration Files
```hcl
resource "nomad_volume" "job_volume" {
  depends_on  = [data.nomad_plugin.ceph-csi]
  type        = "csi"
  plugin_id   = "ceph-csi"
  volume_id   = "job-volume"
  name        = "job-volume"

  capacity_min = "1GB"
  capacity_max = "1GB"

  capability {
    access_mode     = "multi-node-single-writer"
    attachment_mode = "block-device"
  }

  secrets {
    userID  = "admin"
    userKey = "=="
  }

  parameters {
    clusterID     = "ID"
    pool          = "nomadv"
    imageFeatures = "layering"
  }

}
```

### Debug Output
│ Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the
│ equals sign to assign it a value.

### Expected Behavior
The volume should be created

### Actual Behavior
The volume is not created

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by lgfa29** [comment]
Hi @NegativeFeedback 👋 

The error message kind of explains the problem, `parameters` need to have an equal sign since it's a map parameter in the resource (I believe `secret` may need it as well?). This is a bit confusing, but structures without `=` are blocks and they can usually be repeated, key-value configuration are usually defined as map arguments, and so need the `=`.

Try it like this to check if it solves the problem:

```hcl
resource "nomad_volume" "job_volume" {
  depends_on  = [data.nomad_plugin.ceph-csi]
  type        = "csi"
  plugin_id   = "ceph-csi"
  volume_id   = "job-volume"
  name        = "job-volume"

  capacity_min = "1GB"
  capacity_max = "1GB"

  capability {
    access_mode     = "multi-node-single-writer"
    attachment_mode = "block-device"
  }

  secrets = {
    userID  = "admin"
    userKey = "=="
  }

  parameters = {
    clusterID     = "ID"
    pool          = "nomadv"
    imageFeatures = "layering"
  }
}
```

**Comment by NegativeFeedback** [comment]
hmm this did work when I also used "nomad_external_volume" confusing but all good now. Thanks for the help!
