### ISSUE TITLE
Request: Support applying ACLs to workloads

### ISSUE THREAD

**Issue by regner** [hashicorp/terraform-provider-nomad#306]
Nomad has added a built in variables system. Along with that came the ability to manage access to variables with ACL policies. Nomad now has the ability to grant a specific job, group, or task an ACL.

This is a requirement for the tasks to be able to read variables if they are deployed to anything other than the default namespace.

https://developer.hashicorp.com/nomad/docs/concepts/workload-identity#workload-associated-acl-policies

This would require adding optional attributes for namepsace, job, group, and task to the nomad_acl_policy resource.

**Comment by jrasell** [comment]
Hi @regner and thanks for raising this!
