### ISSUE TITLE
Invalid Key "address" Terraform nomad_job

### ISSUE THREAD

**Issue by amardeep-s** [hashicorp/terraform-provider-nomad#311]
Hi there,

I am using terraform latest version to provision nomad jobs. I need to use different IP Address for internal jobs. Reading on how to configure the same I came across configuring the service address as documented here https://github.com/hashicorp/nomad/pull/12720 , terraform throws following error using nomad_job
```

Error: error parsing jobspec: error parsing 'job': 1 error occurred:
│ 	* group: 'mysql', task: 'mysql-server', service (0): invalid key: address
```

When I add that directly into nomad job plan, it works correctly and consul also registers service using address
```
          "Services": [
            {
              "Name": "mysql",
              "TaskName": "mysql-server",
              "PortLabel": "mysql",
              "AddressMode": "auto",
              "Address": "192.168.1.2",
            }
```

I am using latest version.

### Terraform Version

This command will also output the provider version, please include that as well.
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/nomad v1.4.19
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Nomad Version
```
Name                 Address          Port  Status  Leader  Raft Version  Build  Datacenter  Region
desktop.global  192.168.1.2      4648  alive       true        3             1.4.4       dc1         global
```

### Provider Configuration
Which values are you setting in the provider configuration? 

```hcl
      #Service context
      service {
        name = "${mysql_service_name}"
        port = "mysql"
        address = "192.168.1.2"
        provider = "consul"
```

### Affected Resource(s)
- nomad_job

### Expected Behavior
Terraform should not throw invalid key.

### Actual Behavior
Terraform is throwing invalid key error.

Thanks,
Amar

**Comment by amardeep-s** [comment]
Hi There,

Can anyone please suggest on the above issue?

Regards,
Amar

**Comment by lgfa29** [comment]
Hi @amardeep-s 👋 

Apologies for the delay here.

Do you have [HCL2 parsing](https://registry.terraform.io/providers/hashicorp/nomad/latest/docs/resources/job#hcl2-jobspec) enabled? If not, could you try setting this in your job resource and trying again?

```hcl
resource "nomad_job" "..." {
  hcl2 {
    enabled = true
  }
  # ...
}
```

**Comment by tired-engineer** [comment]
Thanks, @lgfa29!
I had the same issue and your advice helped: with hcl2 { enabled = true } "address" field works!

**Comment by lgfa29** [comment]
Glad it worked @tired-engineer. In a future release we'll make that the new default.

@amardeep-s did you have a chance to try this?

**Comment by lgfa29** [comment]
Closing this as https://github.com/hashicorp/terraform-provider-nomad/pull/343 sets HCL2 as the new default.
