### ISSUE TITLE
nomad_acl_binding_rule requires bind_name when it should not

### ISSUE THREAD

**Issue by regner** [hashicorp/terraform-provider-nomad#324]
### Nomad Version
1.5.3

### Affected Resource(s)
Please list the resources as a list, for example:
- nomad_acl_binding_rule

### Terraform Configuration Files
```hcl
resource "nomad_acl_binding_rule" "main" {
  description = "example management rule"
  auth_method = nomad_acl_auth_method.main.name
  selector    = "admin in list.roles"
  bind_type   = "management"
}
```

### Expected Behavior
This should create an ACL binding rule that binds to a management token.

### Actual Behavior
It fails due to requiring the bind_name argument.

### Important Factoids
The Nomad documentation specifies the bind-name argument as optional, and specifically says it should not be provided when the bind type is management.

> [-bind-name](https://developer.hashicorp.com/nomad/docs/commands/acl/binding-rule/create#bind-name): Specifies is the target of the binding used on selector match. This can be lightly templated using HIL ${foo} syntax. If the bind type is set to management, this should not be set.

https://developer.hashicorp.com/nomad/docs/commands/acl/binding-rule/create

Of note, providing an empty string (`""`) does work to get around this.

**Comment by lgfa29** [comment]
Hi @regner 👋 

Thanks for the report! It does seem like we have the wrong validation here:
https://github.com/hashicorp/terraform-provider-nomad/blob/f30b1f6d855fab94bc1278ab8825b7ec5122ee73/nomad/resource_acl_binding_rule.go#L54-L58

I don't think `ValidateFunc` allows you to check across fields, so we may need to perform this validation at run time.

**Comment by regner** [comment]
OK, I will see if I can open a PR to solve that along with a test or two for validating it. Thank you for the response.
