### ISSUE TITLE
template change mode noop being respected.

### ISSUE THREAD

**Issue by rismoney** [hashicorp/terraform-provider-nomad#336]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.2.3

This command will also output the provider version, please include that as well.

### Nomad Version
1.4.20

On a template:
```HCL
      template {
        destination = "local/foo.yml"
        change_mode="noop"
        data = <<-EOF
      ...
EOF
      }
```

Is the expectation on subsequent terraform applies, that changemode here is not applicable, and terraform will kill the task regardless or is this a bug/feature request, and it should be able to update a template on a noop job, without causing a service restart.

**Comment by lgfa29** [comment]
Hi @rismoney 👋 

That `noop` is a runtime configuration of the job,meaning that, if the template changes while the job is running, the task will not be affected.

This does not change the behaviour of Terraform, an in fact this value is transparent to the provider. If your job resource is being recreated even without anything changing then you may be running into https://github.com/hashicorp/terraform-provider-nomad/issues/290.

Would it be possible to share the output of a `terraform plan`?

**Comment by rismoney** [comment]
I am not running into #290.  I believe what you said is correct.    It is sad that it istransparent to the provider, since it would be nice, to be able to modify templates, in particular, without completing/restarting jobs.  For instance if I am running prometheus, and had alerts.yml defined as a template, prometheus can dynamic reload the file on changes.  Right now I am working around this, by decoupling the templated file from from the job, but that is less desireable.

I believe the template can dynamic reload if sourcing from consul key/val, but I think that's also kludgy for storing a big yaml object in consul and becomes obtuse to manage.

Not sure what other options are doable.  Thank you for the reply btw!

**Comment by lgfa29** [comment]
Unfortunately there is not many ways around this. If your jobspec changes in a way that requires a task to be recreated Nomad will have to restart your application. That's why you need a dynamic template pulling data from Consul or Nomad, because then your actual template content will remain the same.

Once the next version of the provider is released with support for Nomad variables you would be able to do something like this:

```hcl
resource "nomad_variable" "config" {
  path = "nomad/jobs/example"
  items = {
    "config" = <<EOF
config:
  value: "Hello"
EOF
  }
}


resource "nomad_job" "example" {
  jobspec = <<EOF
job "example" {
  group "hello" {
    task "hello" {
      driver = "raw_exec"
      config {
        command = "/bin/bash"
        args    = ["$${NOMAD_TASK_DIR}/script.sh"]
      }

      template {
        data        = <<EOH
while true; do
  cat "{{env "NOMAD_TASK_DIR"}}/config.yaml"
  sleep 3
done
EOH
        destination = "$${NOMAD_TASK_DIR}/script.sh"
      }

      template {
        data        = "{{ with nomadVar \"nomad/jobs/example\" }}{{ .config }}{{ end }}"
        destination = "$${NOMAD_TASK_DIR}/config.yaml"
        change_mode = "noop"
      }
    }
  }
}
EOF
}
```

Modifying `nomad_variable.config` updates the file inside the task without restarting it because of the template `noop`.

I'm going to close this since it's not an issue we can solve, but feel free to reach out if you have any other question 🙂
