### ISSUE TITLE
misleading message about hcl2 "enabled" going to `false`

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/terraform-provider-nomad#368]
### Terraform Version
$ terraform -v
Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.11.0
+ provider registry.terraform.io/hashicorp/nomad v2.0.0

### Nomad Version
1.6.1

### Provider Configuration

Provider version: 2.0.0-rc.1 (saved as file name 2.0.0 in the local cache inside `~/.terraform.d/...`

### Affected Resource(s)
Please list the resources as a list, for example:
- nomad_job

### Actual Behavior

When I started using the version 2.0.0-rc.1 (renamed to 2.0.0 on disk) ... I see the following ...

```bash
│ Starting with version 2.0.0 of the Nomad provider, jobs are parsed using HCL2 by default, so this field is no longer used and may be safely removed from your
│ configuration files. Set 'hcl1 = true' if you must use HCL1 job parsing.

```

... so I removed the line `enabled = true` inside the `hcl2` stanza.

Now when I run `terraform plan`, I see the following ...

```hcl
  ~ resource "nomad_job" "myjob" {
      + hcl1                    = false
        id                      = "myjob"
        name                    = "myjob"
      + read_allocation_ids     = false
        # (12 unchanged attributes hidden)

      ~ hcl2 {
          ~ enabled  = true -> false
            # (2 unchanged attributes hidden)
        }
    }

```

### Expected Behavior

As per the warning message, hcl2 is "enabled" by default, so if it is unspecified, it should be treated as `true`.

The `plan` output shows it going to `false`. Is this expected?

### Steps to Reproduce

using the v2.0.0-rc.1 provider version do "plan" and "apply" the job by explicitly setting `enabled = true` in the configuration file.
the remove the line `enabled = true` as suggested in the warning message.

### Important Factoids
provider version 2.0.0-rc.1 has been downloaded and placed inside local cache in `~/.terraform.d/plugins/registry.terraform.io/hashicorp/nomad/2.0.0/linux_amd64/terraform-provider-nomad_v2.0.0_x5`

**Comment by lgfa29** [comment]
Ops, I forgot to flip the default value. Thanks for report @shantanugadgil!

**Comment by shantanugadgil** [comment]
did this make into `2.0.0-rc.2` ?

**Comment by lgfa29** [comment]
Yup! The release is already tagged, but it may take a bit to show up in the registry.
