### ISSUE TITLE
Plan errors out when Nomad variable was deleted outside of Terraform

### ISSUE THREAD

**Issue by Yethal** [hashicorp/terraform-provider-nomad#373]
### Affected Resource(s)
- nomad_variable

### Expected Behavior
Variable should be detected as deleted outside of terraform and terraform should offer to recreate it

### Actual Behavior
Error: error checking for variable nomad/jobs/autoscaler@default: &errors.errorString{s:"variable not found"}
│
│   with nomad_variable.variable["autoscaler"],
│   on jobs.tf line 67, in resource "nomad_variable" "variable":
│   67: resource "nomad_variable" "variable" {

### Steps to Reproduce
1. Add `nomad_variable` resource in terraform
2. Run apply
3. Delete Nomad variable via UI/API
4. Run terraform plan

**Comment by lgfa29** [comment]
Thanks for the report @Yethal.

The variable read method returns a different error than what we usually expect, so it wasn't being handled properly. I opened #374 to fix this.
