### ISSUE TITLE
Namespace in job_acl block in nomad_acl_policy reverts to default after apply

### ISSUE THREAD

**Issue by Yethal** [hashicorp/terraform-provider-nomad#377]
### Nomad Version
1.6.1

### Provider Configuration

```hcl
provider "nomad" {
  ...
}
```

### Affected Resource(s)
- nomad_acl_policy

### Expected Behavior
I expected plan to show no changes

### Actual Behavior
Second plan shows planned change. Namespace field in job_acl block is to be changed from "default" to our namespace

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a nomad namespace
2. Create nomad_acl_policy resource with following content:
```
resource "nomad_acl_policy" "policy" {

  name        =  "somename"
  description = "some description"
  rules_hcl   = file("path to hcl file")

  job_acl {
    namespace = "your namespace here"
    job_id = "some job id"
  }
}
```
3. Run terraform apply to create policy
4. Run terraform plan

**Comment by msherman13** [comment]
https://github.com/hashicorp/terraform-provider-nomad/pull/396

**Comment by lgfa29** [comment]
Hi @msherman13 👋 

With Nomad 1.7 out, I'm going over the remaining open issues and PRs here to prepare the next release. I can't provide any specific date at this point, but a new version should go out next week.

With #396 merged I'm going to close this issue.

Thank you so much for the help @Yethal, @livioribeiro, and @msherman13!

**Comment by msherman13** [comment]
Thanks @lgfa29
