### ISSUE TITLE
jobspec field "crons" is unsupported

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/terraform-provider-nomad#381]
## Description

When trying to apply a nomad job file containing the new(ish) **crons** field an "**Unsupported argument**" error is returned.

### Terraform Version
```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/nomad v2.0.0
```

### Nomad Version
```
Name             Address       Port  Status  Leader  Raft Version  Build  Datacenter  Region
darwinia.global  10.x.x.x      4648  alive   true    3             1.6.2  dc1         global
```

### Provider Configuration

```hcl
provider "nomad" {
  address = "http://10.x.x.x:4646"
}
```

### Environment Variables

```sh
NOMAD_ADDR=http://nomad.service.consul
```

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
```hcl
resource "nomad_job" "everything" {
  for_each = fileset("${path.module}/job", "*.nomad")
  jobspec  = file("job/${each.value}")
  detach   = false
}
```

```hcl
#--- job spec snippet

  periodic {
    // Launch every day
    crons = [
      "0 0 12 * * * *"
    ]
  }

```

### Debug Output
[debug text](https://gist.github.com/tristanmorgan/31b29600f2a0b405200777e92fb11ef9)

### Expected Behavior
The apply should succeed.

### Actual Behavior

The following error was presented
```
╷
│ Error: error parsing jobspec: :10,5-10: Unsupported argument; An argument named "crons" is not expected here. Did you mean "cron"?
│ 
│   with nomad_job.everything["compactor.nomad"],
│   on nomad.tf line 15, in resource "nomad_job" "everything":
│   15: resource "nomad_job" "everything" {
│ 
╵
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Important Factoids

When validating the jobspec with nomad the following warning was presented so I updated the files.
```
Job Warnings:
1 warning:

* cron is deprecated and may be removed in a future release. Use crons instead
```

### References
- Add multiple times in periodic jobs [#17858](https://github.com/hashicorp/nomad/pull/17858)

**Comment by tristanmorgan** [comment]
## Additional Info
If adding `hcl1 = true` the error message changes during apply to the following. but neither usage produce an error during terraform validate. 

```bash
╷
│ Error: error parsing jobspec: error parsing 'job': 1 error occurred:
│ 	* periodic -> invalid key: crons
│ 
│ 
│ 
│   with nomad_job.test,
│   on test.tf line 1, in resource "nomad_job" "test":
│    1: resource "nomad_job" "test" {
│ 
╵
```

**Comment by tristanmorgan** [comment]
Seems the data sources `nomad_job_parser` and `nomad_job` also don't understand "crons" either.

**Comment by jrasell** [comment]
Hi @tristanmorgan and thanks for raising this issue. This seems to be caused by the current Nomad dependency version which is not at the level to include the newly added `crons` job specification parameter. I have raised a PR to fix this.
