### ISSUE TITLE
Support the HCL source when submitting the job

### ISSUE THREAD

**Issue by netdata-be** [hashicorp/terraform-provider-nomad#392]
Hi,

Nomad supports the source parameter when submitting a job to the API.
It will contain the HCLv2 so you could edit the HCL file in the UI instead of the json.

It would be nice that the terraform provider would submit the HCL as well.

**Comment by jrasell** [comment]
Hi @netdata-be and thanks for raising this issue. I agree that would be nice to include within the provider, so I'll mark it as an enhancement.
