### ISSUE TITLE
acl_auth_method: add token name format parameter

### ISSUE THREAD

**Issue by jrasell** [hashicorp/terraform-provider-nomad#394]
Nomad PR https://github.com/hashicorp/nomad/pull/19135 added support for an optional token name format parameter within an ACL authentication method. The Nomad Terraform provider should be updated to support this.

**Comment by the-nando** [comment]
hey @jrasell :) did you get a chance to look at this? I can put together an MR otherwise

**Comment by jrasell** [comment]
Hi @the-nando; I have not got around to this. If you have the ability to raise a PR with this addition, that would be amazing. If you have any questions, feel free to ping me about it.

**Comment by the-nando** [comment]
@jrasell I've tested it on a local cluster and I get the expected result:
```
resource "nomad_acl_auth_method" "test" {
  name           	  = "foo"
  type           	  = "OIDC"
  token_locality 	  = "global"
  token_name_format = "$${auth_method_type}-$${auth_method_name}-$${value.user}"
  max_token_ttl  	  = "10m0s"
  default        	  = "false"

  config {
    oidc_discovery_url    = "https://uk.auth0.com/"
    oidc_client_id        = "someclientid"
    oidc_client_secret    = "someclientsecret-t"
    oidc_scopes           = ["email"]
    bound_audiences       = ["someclientid"]
    discovery_ca_pem      = ["secretpemcert"]
    signing_algs          = ["rsa256", "hs256"]
    allowed_redirect_uris = [
      "http://localhost:4649/oidc/callback",
    ]
    claim_mappings = {
      "http://nomad.internal/name": "name"
    }
    list_claim_mappings = {
      "http://nomad.internal/roles": "roles"
    }
  }
}
```
```
~ curl -s -N --cacert ${NOMAD_CACERT} --cert ${NOMAD_CLIENT_CERT} --key ${NOMAD_CLIENT_KEY} -H "X-Nomad-Token: ${NOMAD_TOKEN}" ${NOMAD_ADDR}/v1/acl/auth-method/foo | jq .TokenNameFormat                                  
"${auth_method_type}-${auth_method_name}-${value.user}"
~
```

The acceptance tests pass as well when run locally but fail when run in [GH](https://github.com/the-nando/terraform-provider-nomad/actions/runs/7205601540/job/19628882718):
```
    resource_acl_auth_method_test.go:26: Step 1/2 error: Check failed: expected token name format to be "${auth_method_type}-${auth_method_name}-${value.user}", is "" in API
--- FAIL: TestResourceACLAuthMethod (0.45s)
```

Do you have any idea what could be wrong here?

**Comment by the-nando** [comment]
I had to update a couple of unrelated tests after the bump to 1.7.1. The OSS acceptance test run clean: https://github.com/the-nando/terraform-provider-nomad/actions/runs/7206010755/job/19630025904
Could you please have a look if it looks ok to you?
