### ISSUE TITLE
csi volume registration docs contradict code

### ISSUE THREAD

**Issue by gastrodon** [hashicorp/terraform-provider-nomad#416]
The [docs](https://registry.terraform.io/providers/hashicorp/nomad/latest/docs/resources/csi_volume_registration#deregister_on_destroy) for `nomad_csi_volume_registration` field `deregister_on_destroy` specifies that it defaults to `false`, but [here](https://github.com/hashicorp/terraform-provider-nomad/blob/main/nomad/resource_csi_volume_registration.go#L248) in the corresponding code it's actually defaulting to true

**Comment by lgfa29** [comment]
Thanks for the report @gastrodon!

I opened #424 to fix the docs with the right default value.
