### ISSUE TITLE
allow data sources to be queried with namespaced identifier

### ISSUE THREAD

**Issue by sbaildon** [hashicorp/terraform-provider-nomad#426]
### Terraform Version
- provider registry.opentofu.org/hashicorp/nomad v2.1.1

### Affected Resource(s)
Please list the resources as a list, for example:
- data.nomad_job
- probably other namespaces data.* sources

### Expected Behavior
https://github.com/hashicorp/terraform-provider-nomad/pull/408 introduced querying resources with a namespace identifier, `<job_id>@<namespace>`, i'd expect the same to be true when querying _data sources_, not only _resources_

### Actual Behavior
404

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/terraform-provider-nomad/pull/408
- https://registry.terraform.io/providers/hashicorp/nomad/latest/docs/data-sources/job

**Comment by lgfa29** [comment]
Hi @sbaildon 👋 

Our documentation is wrong 😅 

You can read a job from a namespace by specifying it in the `data` block itself. I've opened https://github.com/hashicorp/terraform-provider-nomad/pull/427 to fix this and provide a more complete example.

```hcl
data "nomad_job" "example" {
  job_id    = "example"
  namespace = "dev"
}
```
