### ISSUE TITLE
[Feat] Add ability to run nomad actions from terraform.

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/terraform-provider-nomad#432]
Title ^

**Comment by tgross** [comment]
@blmhemu Terraform typically updates a state of some kind. What do you imagine the result of running an action in Terraform to be?

**Comment by blmhemu** [comment]
My particular use case would be run some initial steps after an job has become healthy. This might seem bizzare but some apps leave configuration after they are launched esp php apps but not when launching.

**Comment by blmhemu** [comment]
Also, with regards to the result, most actions tend to be idempotent and the result would just be that - running the action - Usually the first time, ac action is run, there is some change, but afterwards, it can just run and let the change to idempotent.

**Comment by tgross** [comment]
> Also, with regards to the result, most actions tend to be idempotent and the result would just be that - running the action - Usually the first time, ac action is run, there is some change, but afterwards, it can just run and let the change to idempotent.

We don't put any kind of restrictions on what actions do, and plenty of workflows will have non-idempotent actions. And Terraform typically wants to track state of things so that it doesn't run them unnecessarily. For example, how would you `terraform plan` without always getting a dirty plan that needs to be run?

**Comment by tgross** [comment]
@blmhemu what would make those checks? This isn't feeling like it's a good fit for the Terraform provider at all.

**Comment by MatthewJohn** [comment]
@blmhemu Whilst I agree it's not massively what Terraform is for, I have just done something similar:

 * Created a nomad job normally in Terraform
 * Create a second "batch" job, which does the task (setup etc).

The batch job uses some UUID so it gets re-created on each deployment.
I used a template block for giving a connection to the service of the main task - I believe this will only be populated once the service is healthy.
It then runs the import and completes (you can also use the retry for handling failures etc.)
Along with a custom entry-point to run the setup and I  some shared volumes, if required. 

Could this fulfil your use-case?

For reference, here's the code I used: https://gitlab.dockstudios.co.uk/pub/terra/terrareg-nomad-pipeline/-/blob/main/main.tf (and a blog post plug, if it helps :P https://blog.mattsbit.co.uk/2024/02/22/gitlab-ephemeral-environments-for-pull-requests/)

**Comment by tgross** [comment]
Thanks @MatthewJohn.

I'm going to close this issue, as I think this isn't a direction we want to go for the Terraform provider.
