### ISSUE TITLE
Add sensitive flag to avoid outputting job spec

### ISSUE THREAD

**Issue by analytically** [hashicorp/terraform-provider-nomad#91]
It'd be handy to be able to specify 'sensitive: true' for a nomad_job so it won't output the jobspec to stdout. Job specs often contain environment vars with sensitive info (passwords) and CI tools then have this in their logs.

**Comment by remilapeyre** [comment]
This would mean the diff is always hidden and you would never be able to see what changes exactly would get deployed. We had the same needs for the Consul provider at https://github.com/terraform-providers/terraform-provider-consul/issues/159 but ultimately decided against it as it would decrease the usability of the provider for the general usage and secrets should be stored in Vault. I suspect the same may apply for Nomad.

**Comment by analytically** [comment]
At the same time this disables most usage of Consul/Nomad without strict Vault integration.

**Comment by lgfa29** [comment]
Hi @analytically, 

There are definitely pros and cons on marking `jobspec` as sensitive, and what @remilapeyre pointed out is a significant drawback in many cases.

[Terraform 0.14 added the capability of marking input variables as sensitive](https://www.hashicorp.com/blog/terraform-0-14-adds-the-ability-to-redact-sensitive-values-in-console-output). This allows marking `jobspec` as sensitive when needed, without having to modify the provider.

You would need to wrap `nomad_job` in a module. Something like this:

```hcl
variable "jobspec" {
  type      = string
  sensitive = true
}

resource "nomad_job" "job" {
  jobspec = var.jobspec
}
```

Then you Terraform commands will hide the jobspec:

```
  # module.sensitive_job.nomad_job.job will be created
  + resource "nomad_job" "job" {
      + allocation_ids          = (known after apply)
      + datacenters             = [
          + "dc1",
        ]
      + deployment_id           = (known after apply)
      + deployment_status       = (known after apply)
      + deregister_on_destroy   = true
      + deregister_on_id_change = true
      + detach                  = true
      + id                      = (known after apply)
      + jobspec                 = (sensitive)
      + modify_index            = (known after apply)
      + name                    = "consul-register-on-update"
      + namespace               = "default"
      + region                  = (known after apply)
      + task_groups             = [
          + {
              + count   = 1
              + meta    = (known after apply)
              + name    = "echo"
              + task    = [
                  + {
                      + driver        = "docker"
                      + meta          = (known after apply)
                      + name          = "busybox-nc"
                      + volume_mounts = null
                    },
                ]
              + volumes = null
            },
        ]
      + type                    = "service"
    }
```

The good thing about this is that marking `jobspec` as sensitive then becomes an opt-in action that you can use when necessary. The downside is having to create a module, but it would be a small one.

What do you think of this approach?

**Comment by lgfa29** [comment]
Hi @analytically,

I'm closing this issue for now, but feel free to let us know if the proposed is not enough.
